add H.265/HEVC 8K
c-alpha/metadata-website pull request #9
Opened 2021-06-21 18:49 UTC by paulhiggs

This PR adds new classification schemes for VideoCodecCS:2021 and VideoConformancePointsCS:2021 which include 8K HEVC/H.265.
These CS's are already referenced by the A177r2 specification approved by TM last week.

2021-06-22 08:52 UTC, paulhiggs commented
remove additional end tags - make formatting more 'user friendly'

2021-06-22 16:57 UTC, c-alpha commented
Hello Paul, many thanks for your swift action and this PR! Are you expecting to add further commits to this?

2021-06-22 17:07 UTC, paulhiggs commented
No, that's it.
________________________________
From: Alexander Adolf ***@***.***>
Sent: Tuesday, June 22, 2021 5:57:38 PM
To: c-alpha/metadata-website ***@***.***>
Cc: Paul Higgs ***@***.***>; Author ***@***.***>
Subject: Re: [c-alpha/metadata-website] add H.265/HEVC 8K (#9)


Hello Paul, many thanks for your swift action and this PR! Are you expecting to add further commits to this?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/c-alpha/metadata-website/pull/9#issuecomment-866162884>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAYDGF5KQXX4H5HFXIYKQADTUC6IFANCNFSM47CEH7CQ>.

2021-06-23 10:45 UTC, c-alpha requested changes

2021-06-23 10:45 UTC, c-alpha commented on metadata/cs/VideoCodecCS.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Can you make this file a symbolic link to your 2021 version, please?

2021-06-23 10:45 UTC, c-alpha commented on metadata/cs/VideoConformancePointsCS.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Can you make this file a symbolic link to your 2021 version, please?

2021-06-23 11:50 UTC, paulhiggs commented
Done. Also added another commit to update the DVB.zip bundle with the new CSs
________________________________
From: Alexander Adolf ***@***.***>
Sent: Wednesday, June 23, 2021 11:45:30 AM
To: c-alpha/metadata-website ***@***.***>
Cc: Paul Higgs ***@***.***>; Author ***@***.***>
Subject: Re: [c-alpha/metadata-website] add H.265/HEVC 8K (#9)


@c-alpha requested changes on this pull request.

________________________________

In metadata/cs/VideoCodecCS.xml<https://github.com/c-alpha/metadata-website/pull/9#discussion_r656409188>:

> \ No newline at end of file
+<?xml version="1.0" encoding="UTF-8"?>


Can you make this file a symbolic link to your 2021 version, please?

________________________________

In metadata/cs/VideoConformancePointsCS.xml<https://github.com/c-alpha/metadata-website/pull/9#discussion_r656409500>:

> \ No newline at end of file
+<?xml version="1.0" encoding="UTF-8"?>


Can you make this file a symbolic link to your 2021 version, please?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/c-alpha/metadata-website/pull/9#pullrequestreview-689768591>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAYDGF4GNQYDHD64VH7MKGLTUG3MVANCNFSM47CEH7CQ>.

2021-06-23 11:58 UTC, c-alpha commented
> Also added another commit to update the DVB.zip bundle with the new CSs.

Cool! I presume you used the `Makefile` to generate it?

2021-06-23 12:07 UTC, paulhiggs commented
Um, no as I do not have 'zip' on my systems. Perhaps the ZIP file is something that can be created through CI/CD routines triggered on a merge.
________________________________
From: Alexander Adolf ***@***.***>
Sent: Wednesday, June 23, 2021 12:58:41 PM
To: c-alpha/metadata-website ***@***.***>
Cc: Paul Higgs ***@***.***>; Author ***@***.***>
Subject: Re: [c-alpha/metadata-website] add H.265/HEVC 8K (#9)


Also added another commit to update the DVB.zip bundle with the new CSs.

Cool! I presume you used the Makefile to generate it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/c-alpha/metadata-website/pull/9#issuecomment-866774114>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAYDGF66ZRMQLOWYPHVZZB3TUHD7DANCNFSM47CEH7CQ>.

2021-06-23 12:11 UTC, c-alpha commented
No worries; I can create the zip easily. There are a couple of further fixes I want to apply (bug 2872 & friends) before making the next release, so I'll wrap it into that.

Many thanks!

2021-06-23 12:31 UTC, c-alpha approved these changes

2021-06-23 12:51 UTC, merged